# Mock Database - Veículos Pré-cadastrados (UK)
VEHICLE_DATABASE = {
    'AB12CDE': {
        'plate': 'AB12 CDE',
        'make': 'ford',
        'make_name': 'Ford',
        'model': 'Fiesta',
        'year': '2012',
        'color': 'Azul',
        'fuel': 'Gasolina',
        'version': '1.0 EcoBoost Titanium',
        'category': 'Hatchback',
        'power': '125cv',
        'transmission': 'Manual',
        'doors': '5',
        'engine_size': '998cc',
        'co2': '109g/km',
        'mpg': '60.1',
        'country': 'UK'
    },
    'CD34FGH': {
        'plate': 'CD34 FGH',
        'make': 'volkswagen',
        'make_name': 'Volkswagen',
        'model': 'Golf',
        'year': '2015',
        'color': 'Prata',
        'fuel': 'Diesel',
        'version': '2.0 TDI GT',
        'category': 'Hatchback',
        'power': '150cv',
        'transmission': 'Manual',
        'doors': '5',
        'engine_size': '1968cc',
        'co2': '106g/km',
        'mpg': '70.6',
        'country': 'UK'
    },
    'EF56IJK': {
        'plate': 'EF56 IJK',
        'make': 'bmw',
        'make_name': 'BMW',
        'model': '3 Series',
        'year': '2018',
        'color': 'Preto',
        'fuel': 'Diesel',
        'version': '320d M Sport',
        'category': 'Sedan',
        'power': '190cv',
        'transmission': 'Automático',
        'doors': '4',
        'engine_size': '1995cc',
        'co2': '112g/km',
        'mpg': '65.7',
        'country': 'UK'
    },
    'GH67LMN': {
        'plate': 'GH67 LMN',
        'make': 'audi',
        'make_name': 'Audi',
        'model': 'A4',
        'year': '2017',
        'color': 'Branco',
        'fuel': 'Gasolina',
        'version': '2.0 TFSI S Line',
        'category': 'Sedan',
        'power': '252cv',
        'transmission': 'Automático',
        'doors': '4',
        'engine_size': '1984cc',
        'co2': '145g/km',
        'mpg': '44.1',
        'country': 'UK'
    },
    'IJ18OPQ': {
        'plate': 'IJ18 OPQ',
        'make': 'mercedes',
        'make_name': 'Mercedes-Benz',
        'model': 'C-Class',
        'year': '2018',
        'color': 'Cinza',
        'fuel': 'Diesel',
        'version': 'C220d AMG Line',
        'category': 'Sedan',
        'power': '194cv',
        'transmission': 'Automático',
        'doors': '4',
        'engine_size': '1950cc',
        'co2': '117g/km',
        'mpg': '63.2',
        'country': 'UK'
    },
    'KL20RST': {
        'plate': 'KL20 RST',
        'make': 'landrover',
        'make_name': 'Land Rover',
        'model': 'Range Rover Sport',
        'year': '2020',
        'color': 'Preto',
        'fuel': 'Diesel',
        'version': 'HSE Dynamic',
        'category': 'SUV',
        'power': '306cv',
        'transmission': 'Automático',
        'doors': '5',
        'engine_size': '2993cc',
        'co2': '213g/km',
        'mpg': '34.9',
        'country': 'UK'
    },
    'MN22UVW': {
        'plate': 'MN22 UVW',
        'make': 'nissan',
        'make_name': 'Nissan',
        'model': 'Qashqai',
        'year': '2022',
        'color': 'Vermelho',
        'fuel': 'Gasolina',
        'version': '1.3 DIG-T Tekna',
        'category': 'SUV',
        'power': '140cv',
        'transmission': 'Manual',
        'doors': '5',
        'engine_size': '1332cc',
        'co2': '145g/km',
        'mpg': '44.1',
        'country': 'UK'
    },
    'OP19XYZ': {
        'plate': 'OP19 XYZ',
        'make': 'vauxhall',
        'make_name': 'Vauxhall',
        'model': 'Corsa',
        'year': '2019',
        'color': 'Branco',
        'fuel': 'Gasolina',
        'version': '1.2 Turbo SRi',
        'category': 'Hatchback',
        'power': '100cv',
        'transmission': 'Manual',
        'doors': '5',
        'engine_size': '1199cc',
        'co2': '118g/km',
        'mpg': '54.3',
        'country': 'UK'
    },
    'QR21ABC': {
        'plate': 'QR21 ABC',
        'make': 'mini',
        'make_name': 'Mini',
        'model': 'Cooper',
        'year': '2021',
        'color': 'Verde',
        'fuel': 'Gasolina',
        'version': 'Cooper S',
        'category': 'Hatchback',
        'power': '178cv',
        'transmission': 'Manual',
        'doors': '3',
        'engine_size': '1998cc',
        'co2': '138g/km',
        'mpg': '46.3',
        'country': 'UK'
    },
    'ST23DEF': {
        'plate': 'ST23 DEF',
        'make': 'tesla',
        'make_name': 'Tesla',
        'model': 'Model 3',
        'year': '2023',
        'color': 'Branco Pérola',
        'fuel': 'Elétrico',
        'version': 'Long Range',
        'category': 'Sedan',
        'power': '346cv',
        'transmission': 'Automático',
        'doors': '4',
        'engine_size': 'Elétrico',
        'co2': '0g/km',
        'mpg': 'N/A',
        'country': 'UK'
    },
    'UV17GHI': {
        'plate': 'UV17 GHI',
        'make': 'mazda',
        'make_name': 'Mazda',
        'model': 'CX-5',
        'year': '2017',
        'color': 'Vermelho',
        'fuel': 'Diesel',
        'version': '2.2 Skyactiv-D Sport Nav',
        'category': 'SUV',
        'power': '175cv',
        'transmission': 'Automático',
        'doors': '5',
        'engine_size': '2191cc',
        'co2': '129g/km',
        'mpg': '57.6',
        'country': 'UK'
    },
    'WX24JKL': {
        'plate': 'WX24 JKL',
        'make': 'hyundai',
        'make_name': 'Hyundai',
        'model': 'Tucson',
        'year': '2024',
        'color': 'Preto',
        'fuel': 'Híbrido',
        'version': '1.6 T-GDi Ultimate',
        'category': 'SUV',
        'power': '230cv',
        'transmission': 'Automático',
        'doors': '5',
        'engine_size': '1598cc',
        'co2': '139g/km',
        'mpg': '46.3',
        'country': 'UK'
    },
    'YZ16MNO': {
        'plate': 'YZ16 MNO',
        'make': 'peugeot',
        'make_name': 'Peugeot',
        'model': '3008',
        'year': '2016',
        'color': 'Prata',
        'fuel': 'Diesel',
        'version': '1.6 BlueHDi Allure',
        'category': 'SUV',
        'power': '120cv',
        'transmission': 'Manual',
        'doors': '5',
        'engine_size': '1560cc',
        'co2': '109g/km',
        'mpg': '68.9',
        'country': 'UK'
    },
    'AB70PQR': {
        'plate': 'AB70 PQR',
        'make': 'jaguar',
        'make_name': 'Jaguar',
        'model': 'F-Pace',
        'year': '2020',
        'color': 'Preto',
        'fuel': 'Diesel',
        'version': '2.0d R-Sport',
        'category': 'SUV',
        'power': '204cv',
        'transmission': 'Automático',
        'doors': '5',
        'engine_size': '1999cc',
        'co2': '166g/km',
        'mpg': '44.8',
        'country': 'UK'
    },
    'CD19STU': {
        'plate': 'CD19 STU',
        'make': 'volvo',
        'make_name': 'Volvo',
        'model': 'XC40',
        'year': '2019',
        'color': 'Azul',
        'fuel': 'Gasolina',
        'version': 'T4 R-Design',
        'category': 'SUV',
        'power': '190cv',
        'transmission': 'Automático',
        'doors': '5',
        'engine_size': '1969cc',
        'co2': '163g/km',
        'mpg': '39.2',
        'country': 'UK'
    },
    'EF22VWX': {
        'plate': 'EF22 VWX',
        'make': 'honda',
        'make_name': 'Honda',
        'model': 'Civic',
        'year': '2022',
        'color': 'Branco',
        'fuel': 'Gasolina',
        'version': '1.5 VTEC Turbo Sport',
        'category': 'Hatchback',
        'power': '182cv',
        'transmission': 'Manual',
        'doors': '5',
        'engine_size': '1498cc',
        'co2': '141g/km',
        'mpg': '45.6',
        'country': 'UK'
    },
    'GH21YZA': {
        'plate': 'GH21 YZA',
        'make': 'toyota',
        'make_name': 'Toyota',
        'model': 'Corolla',
        'year': '2021',
        'color': 'Bronze',
        'fuel': 'Híbrido',
        'version': '2.0 VVT-i Design',
        'category': 'Hatchback',
        'power': '184cv',
        'transmission': 'Automático',
        'doors': '5',
        'engine_size': '1987cc',
        'co2': '102g/km',
        'mpg': '62.8',
        'country': 'UK'
    },
    'IJ23BCD': {
        'plate': 'IJ23 BCD',
        'make': 'seat',
        'make_name': 'Seat',
        'model': 'Leon',
        'year': '2023',
        'color': 'Vermelho',
        'fuel': 'Gasolina',
        'version': '1.5 TSI EVO FR',
        'category': 'Hatchback',
        'power': '130cv',
        'transmission': 'Manual',
        'doors': '5',
        'engine_size': '1498cc',
        'co2': '128g/km',
        'mpg': '50.4',
        'country': 'UK'
    },
    'KL18EFG': {
        'plate': 'KL18 EFG',
        'make': 'skoda',
        'make_name': 'Skoda',
        'model': 'Octavia',
        'year': '2018',
        'color': 'Cinza',
        'fuel': 'Diesel',
        'version': '2.0 TDI SE L',
        'category': 'Perua',
        'power': '150cv',
        'transmission': 'Manual',
        'doors': '5',
        'engine_size': '1968cc',
        'co2': '114g/km',
        'mpg': '65.7',
        'country': 'UK'
    },
    'MN20HIJ': {
        'plate': 'MN20 HIJ',
        'make': 'renault',
        'make_name': 'Renault',
        'model': 'Clio',
        'year': '2020',
        'color': 'Vermelho',
        'fuel': 'Gasolina',
        'version': '1.0 TCe RS Line',
        'category': 'Hatchback',
        'power': '100cv',
        'transmission': 'Manual',
        'doors': '5',
        'engine_size': '999cc',
        'co2': '115g/km',
        'mpg': '55.4',
        'country': 'UK'
    }
}

def search_vehicle_by_plate(plate: str):
    """
    Busca veículo pela placa no banco mock
    Normaliza a placa para uppercase e remove espaços/hífens
    """
    clean_plate = plate.replace('-', '').replace(' ', '').upper()
    return VEHICLE_DATABASE.get(clean_plate)
